spring.application.name=barber-shop-booking

# Server
server.port=${PORT:8080}

# Datasource (override via environment variables in prod)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/barbershop}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

